pit {
  spark {
    app-name = "pit-fundamentals-lakehouse"
    app-name = ${?PIT_APP_NAME}
    master = null
    master = ${?PIT_SPARK_MASTER}
  }
  paths {
    source-dir      = ${?PIT_SOURCE_DIR}
    bronze-root     = ${?PIT_BRONZE_ROOT}
    silver-root     = ${?PIT_SILVER_ROOT}
    gold-root       = ${?PIT_GOLD_ROOT}
    quarantine-root = ${?PIT_QUARANTINE_ROOT}
    registry-path   = ${?PIT_REGISTRY_PATH}
  }
  ingest {
    quarters = ["2023q1"]
    quarters = ${?PIT_QUARTERS}
  }
}
